base_url = "https://atinb.me"
title = "atin"

compile_sass = true
build_search_index = false

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
menu = [
    { name = "/cstf", weight = 1 },
    { name = "/posts", weight = 2 },
]

socials = [
    { name = "gh", url = "https://github.com/atinbainada" },
    { name = "so", url = "https://stackoverflow.com/users/12011589/atin" }
]
